### PR TITLE
Corrected fly bug and doc

### PR DESCRIPTION
**Pull request by Xalares**
Corrected status unhandled for opcode responsible for flying, and added files to the doxygen setting file.
Now to generate doc, only one command is needed in the root folder, doxygen Doxyfile.in

### CODE REVIEW

**Comment by Elmsroth** [comment]
@Xalares now you can fly ?

**Comment by Xalares** [comment]
Yes, now normally you can fly. But be cautious, even if none of the bug mentioned on the website, are present on my build, look if they are present when you build yours.

**Comment by billy1arm** [comment]
@Xalares sorry to be picky, could you separate out the doxygen change from the flying changes

**Comment by Xalares** [comment]
@billy1arm I'll do that

**Pull request closed without merging**
