### PR TITLE
Fixes two build errors.

### PR DESCRIPTION
**Pull request by i-am-fyre**
Removing this line fixes a build error.

---
This change is [Reviewable](https://reviewable.io/reviews/mangosthree/server/9)

### CODE REVIEW

**Review by billy1arm — CHANGES_REQUESTED** [review]
Have you tested on Windows using this change, I suspect it won't build

**Comment by i-am-fyre** [comment]
Will test later tonight.

**Comment by andybe** [comment]
- "define.h" is a typo" and
- I got no flag with  ACE_USE_EXTERNAL = ON  in my dockerfile.

https://github.com/mangosthree/server/pull/11

in my case this pullrequest can be ignored because of Rel22

**Comment by billy1arm** [comment]
fixes are being made to the rel22 branch

**Pull request closed without merging**
